### ISSUE TITLE
bss_file.c

### ISSUE THREAD

**Issue by mercertom** [majal/maj-scripts#3]
I keep getting

At main.c:158:
- SSL error:02001002:system library:fopen:No such file or directory: bss_file.c:175
- SSL error:2006D080:BIO routines:BIO_new_file:no such file: bss_file.c:178
sign-file: ./MOK.priv: No such file or directory
vboxdrv: 
modprobe: ERROR: could not insert 'vboxdrv': Required key not available
Failed to load vboxdrv

Maybe I'm newb, no idea where to from here. Searched on bss_file.c errors on google/askubuntu/github/stackexchange coming up with no solution.

**Comment by majal** [comment]
The error says: `sign-file: ./MOK.priv: No such file or directory`
That means that it cannot find your private key file. So it could be either be:

1. You were not able to create the keys. (http://askubuntu.com/questions/760671/768310#768310)

or

2. You haven't set the working directory in `vboxsign` line 8: `dir=/home/directory/of/keys`
