### ISSUE TITLE
modinfo: ERROR: Module vboxdrv not found.

### ISSUE THREAD

**Issue by mercertom** [majal/maj-scripts#4]
I set the working directory correctly, but I'm getting this error. What do I need to do differently?

sudo sh ~/vboxsign.sh 

modinfo: ERROR: Module vboxdrv not found.

**Comment by majal** [comment]
I'm not sure really, but the script was designed and tested for `bash`... So could you try this instead of calling `sh`?

`$ chmod +x vboxsign`
`$ ./vboxsign`
